image: rustlang/rust:nightly-buster

variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build
  - test
  - deploy

before_script:
  - apt update && apt install -y libzmq3-dev cmake >> /dev/null


build:stable:
  image: "rust:bullseye"
  stage: build
  cache:
    key: debug
    paths:
    - target/debug
  script:
    - cargo build

build:nightly:
  stage: build
  cache:
    key: debug
    paths:
    - target/debug
  script:
    - cargo build


build:deb:
  image: "rust:bullseye"
  needs: ["build:stable"]
  stage: build
  cache:
    key: release
    paths:
    - target/debian
  script:
    - cargo install cargo-deb
    - cargo deb
  artifacts:
    paths:
      - target/debian


build:doc:
  stage: build
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc

test:test:
  stage: test
  cache:
    key: debug
    paths:
    - target/debug
  script:
    - cargo test


test:deb:bullseye:
  image: debian:bullseye-slim
  stage: test
  needs: ["build:deb"]
  script:
    - cp -v target/debian/requestd*.deb ./requestd.deb
    - dpkg -i requestd.deb
    - "[ -e /etc/requestd.yml ]"
    - requestd --help
    - requestd config -d


pages:
  stage: deploy
  only:
    - master
  needs: ["build:deb", "test:test", "test:deb:bullseye"]
  before_script:
    - apt update && apt install -y libzmq3-dev:amd64
  script:
    - mkdir -p public
    - cp -r target/doc/* public/
    - cp -vr target/debian/*.deb public/requestd.deb
  artifacts:
    paths:
      - public
