image: rustlang/rust:nightly-buster

variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build
  - test
  - deploy

before_script:
  - apt update && apt install -y libzmq3-dev >> /dev/null


build:build:
  stage: build
  tags: ['kadse']
  cache:
    key: debug
    paths:
    - target/debug
  script:
    - cargo build


build:deb:
  stage: build
  cache:
    key: release
    paths:
    - target/debug
  script:
    - cargo install cargo-deb
    - cargo deb
  artifacts:
    paths:
      - target/debian


build:doc:
  stage: build
  cache:
    key: debug
    paths:
      - target/debug
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc


test:test:
  stage: test
  needs: ["build:build"]
  cache:
    key: debug
    paths:
    - target
  script:
    - cargo test

test:deb:
  stage: test
  needs: ["build:deb"]
  cache:
    key: release
    paths:
    - target/release
  script:
    - apt update && apt install -y python3-prometheus-client
    - dpkg -i target/debian/*.deb
    - "[ -e /etc/requestd.yml ]"
    - requestd --help >> /dev/null



pages:
  stage: deploy
  only:
    - master
  needs: ["build:deb", "build:doc", "test:test", "test:deb"]
  before_script:
    - apt update && apt install -y libzmq3-dev:amd64
  script:
    # - cargo install cargo-deb
    # - cargo deb
    # - cargo doc
    - mkdir -p public
    - cp -r target/doc/* public/
    - cp -vr target/debian/*.deb public/requestd.deb
  artifacts:
    paths:
      - public
