image: "rust:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - target/debug
    - target/release
    - target/doc

stages:
  - build
  - test
  - deploy

before_script:
  - apt update && apt install -y libzmq3-dev:amd64

build:build:
  stage: build
  script:
    - cargo update
    - cargo build
  artifacts:
    paths:
      - target

test:test:
  stage: build
  script:
    - cargo test

build:deb:
  stage: build
  script:
    - cargo install cargo-deb
  artifacts:
    paths:
      - target/debian

deploy:doc:
  stage: build
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc

pages:
  stage: deploy
  only:
    - master
    - develop
  needs: ["build:deb", "deploy:doc"]
  script:
    - mkdir -p public
    - cp -r target/doc/* public/
    - cp -r target/debian/*.deb public/requestd.deb
  artifacts:
    paths:
      - public
