image: "rust:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt update && apt install -y libzmq3-dev:amd64

cache:
  paths:
  - target/debug
  - target/release
  - target/doc

stages:
  - build
  - test
  - deploy


build:build:
  stage: build
  script:
  - cargo update
  - cargo build
  artifacts:
    paths:
    - target


test:test:
  stage: test
  script:
  - cargo test

deploy:deb:
  needs: test:test
  script:
  - cargo install cargo-deb
  artifacts:
    paths:
    - target/debian

deploy:docs:
  script:
  - cargo doc
  artifacts:
    paths:
    - target/doc


pages:
  stage: deploy
  needs: ['deploy:deb', 'deploy:doc']
  script:
  - mkdir -p public
  - cp -r target/doc/* public/
  - cp -r target/debian/*.deb public/latest.deb
  artifacts:
    paths:
    - public
