image: "rust:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt update && apt install -y libzmq3-dev:amd64

cache:
  paths:
  - target/

stages:
  - build
  - test
  - deploy


build:build:
  stage: build
  script:
  - cargo update
  - cargo build
  artifacts:
    paths:
    - target


test:test:
  stage: test
  script:
  - cargo test


pages:
  stage: deploy
  needs: ['build:build', 'test:test']
  script:
  - cargo install cargo-deb
  - mkdir -p public
  - cargo doc
  - cp -r target/doc/* public/
  - cargo deb
  - cp -r target/debian/*.deb public/latest.deb
  artifacts:
    paths:
    - public
