image: "rust:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt update && apt install -y libzmq3-dev:amd64

cache:
  paths:
  - target/

stages:
  - build
  - test
  - deploy


build:build:
  stage: build
  script:
  - cargo update
  - cargo build
  artifacts:
    paths:
    - target


test:test:
  stage: test
  script:
  - cargo test


deb_package:
  stage: deploy
  script:
  - cargo install cargo-deb
  - cargo deb
  artifacts:
    paths:
    - target/deb


pages:
  stage: deploy
  dependencies:
  - deb_package
  script:
  - mkdir -p public
  - cp -r target/debian/*.deb public/ffhl-collector_latest.deb
  artifacts:
    paths:
    - public
