image: "rust:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
  - target/debug
  - target/release
  - target/doc

stages:
  - build
  - test
  - deploy


build:build:
  stage: build
  before_script:
  - apt update && apt install -y libzmq3-dev:amd64
  script:
  - cargo update
  - cargo build
  artifacts:
    paths:
    - target


test:test:
  stage: build
  before_script:
  - apt update && apt install -y libzmq3-dev:amd64
  script:
  - cargo test

build:deb:
  stage: build
  before_script:
  - apt update && apt install -y libzmq3-dev:amd64
  script:
  - cargo install cargo-deb
  artifacts:
    paths:
    - target/debian

deploy:doc:
  stage: build
  script:
  - cargo doc
  artifacts:
    paths:
    - target/doc


pages:
  stage: deploy
  needs: ['build:deb', 'deploy:doc']
  before_script:
  - apt update && apt install -y libzmq3-dev:amd64
  - cargo install cargo-deb
  script:
  - cargo doc
  - cargo deb
  - mkdir -p public
  - cp -r target/doc/* public/
  - cp -r target/debian/*.deb public/latest.deb
  artifacts:
    paths:
    - public
