image: rustlang/rust:nightly

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - target

stages:
  - build
  - test
  - deploy


build:build:
  stage: build
  before_script:
    - apt update && apt install -y libzmq3-dev:amd64
  script:
    - cargo update
    - cargo build
  artifacts:
    paths:
      - target

test:test:
  stage: test
  before_script:
    - apt update && apt install -y libzmq3-dev:amd64
  script:
    - cargo test

build:deb:
  stage: build
  before_script:
    - apt update && apt install -y libzmq3-dev:amd64
    - cargo install cargo-deb
  script:
    - cargo deb
  artifacts:
    paths:
      - target/debian

build:doc:
  stage: build
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc

pages:
  stage: deploy
  only:
    - master
  needs: ["build:deb", "build:doc"]
  before_script:
    - apt update && apt install -y libzmq3-dev:amd64
  script:
    # - cargo install cargo-deb
    # - cargo deb
    # - cargo doc
    - mkdir -p public
    - cp -r target/doc/* public/
    - cp -r target/debian/*.deb public/requestd.deb
  artifacts:
    paths:
      - public
