image: "rust:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt update && apt install -y libzmq3-dev:amd64

cache:
  paths:
  - target/

stages:
  - build
  - test
  - deploy


build:build:
  stage: build
  script:
  - cargo update
  - cargo build

build:docs:
  stage: build
  allow_failure: true
  artifacts:
    paths:
    - target
  script:
  - cargo update
  - cargo doc

test:test:
  stage: test
  script:
  - cargo test


deb_package:
  stage: deploy
  script:
  - cargo install cargo-deb
  - cargo deb
  - cp -r target/doc/* public/
  artifacts:
    paths:
    - target/debian/


pages:
  stage: deploy
  dependencies:
  - build:docs
  script:
  - mkdir public
  - cp -r target/doc/* public/
  artifacts:
    paths:
    - public
