image: "rust:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt update && apt install -y libzmq3-dev:amd64

cache:
  paths:
  - target/debug
  - target/release
  - target/doc


build:build:
  script:
  - cargo update
  - cargo build
  artifacts:
    paths:
    - target


test:test:
  script:
  - cargo test

build:deb:
  needs: ["test:test"]
  script:
  - cargo install cargo-deb
  artifacts:
    paths:
    - target/debian

deploy:doc:
  script:
  - cargo doc
  artifacts:
    paths:
    - target/doc


pages:
  needs: ['deploy:deb', 'deploy:doc']
  script:
  - mkdir -p public
  - cp -r target/doc/* public/
  - cp -r target/debian/*.deb public/latest.deb
  artifacts:
    paths:
    - public
