image: "rust:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git submodule init
  - git submodule update --recursive
  - rustup default nightly

cache:
  paths:
  - target/

stages:
  - build
  - test
  - deploy


build:build:
  stage: build
  script:
  - cargo update
  - cargo build

build:docs:
  stage: build
  allow_failure: true
  artifacts:
    paths:
    - target
  before_script: # workaround for a bug in nightly
  - rustup default stable
  script:
  - cargo update
  - cargo doc

test:test:
  stage: test
  script:
  - cargo test


pages:
  stage: deploy
  dependencies:
  - build:docs
  script:
  - mkdir public
  - cp -r target/doc/* public/
  artifacts:
    paths:
    - public
