[package]
name = "ffhl-collector"
version = "0.0.0"
authors = ["Paul Maruhn <paulmaruhn@posteo.de>"]
edition = "2018"
homepage = "https://gitlab.com/freifunk-luebeck/ffhl-stats"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
clap = "2.33"
crossbeam-channel = "0.4"
curl = "0.4"
flate2 = "1.0"
libc = "0.2"
log = "0.4"
pretty_env_logger = "0.4"
rusqlite = {version = "0.21", features = ["chrono", "serde_json"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.8"
zmq = "0.9.2"
jq-rs = {version = "0.4.1", features = ["bundled"]}
lazy_static = "1.4"


[profile.release]
panic="abort"


[package.metadata.deb]
name = "ffhl-collector"
depends = "$auto"
build-depends = "libsqlite3-dev libzmq3-dev"
assets = [
	["assets/ffhl-collector.service", "/etc/systemd/system/", "664"],
	["assets/config.yml", "/etc/ffhl-collector.yml", "664"],
	["target/release/ffhl-collector", "usr/bin/", "755"]
]
