sudo: true

language: rust

rust:
  - stable
cache: cargo

before_install:
    - wget https://dl.influxdata.com/influxdb/releases/influxdb_1.5.0_amd64.deb
    - sudo dpkg -i influxdb_1.5.0_amd64.deb
    - sudo /usr/bin/influxd > $HOME/influx.log 2>&1 &

script:
  - cargo build --verbose --all
  - cargo test
  
after_script:
  - cat $HOME/influx.log
